/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as ExportDotzipRouteImport } from './routes/export[.]zip'
import { Route as FloorDatabaseDottxtRouteImport } from './routes/floor-database[.]txt'
import { Route as LoadRouteImport } from './routes/load'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as BlankSheetRouteImport } from './routes/blank.$sheet'
import { Route as DumpSheetRouteImport } from './routes/dump.$sheet'
import { Route as SalesSoNumberRouteImport } from './routes/sales.$soNumber'
import { Route as TicketsTicketNumberRouteImport } from './routes/tickets.$ticketNumber'
import { Route as TicketsNewRouteImport } from './routes/tickets.new'
import { Route as WorkOrdersWoNumberRouteImport } from './routes/work-orders.$woNumber'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportDotzipRoute = ExportDotzipRouteImport.update({
  id: '/export.zip',
  path: '/export.zip',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorDatabaseDottxtRoute = FloorDatabaseDottxtRouteImport.update({
  id: '/floor-database.txt',
  path: '/floor-database.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadRoute = LoadRouteImport.update({
  id: '/load',
  path: '/load',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankSheetRoute = BlankSheetRouteImport.update({
  id: '/blank/$sheet',
  path: '/blank/$sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const DumpSheetRoute = DumpSheetRouteImport.update({
  id: '/dump/$sheet',
  path: '/dump/$sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSoNumberRoute = SalesSoNumberRouteImport.update({
  id: '/$soNumber',
  path: '/$soNumber',
  getParentRoute: () => SalesRoute,
} as any)
const TicketsTicketNumberRoute = TicketsTicketNumberRouteImport.update({
  id: '/$ticketNumber',
  path: '/$ticketNumber',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsNewRoute = TicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TicketsRoute,
} as any)
const WorkOrdersWoNumberRoute = WorkOrdersWoNumberRouteImport.update({
  id: '/$woNumber',
  path: '/$woNumber',
  getParentRoute: () => WorkOrdersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/export.zip': typeof ExportDotzipRoute
  '/floor-database.txt': typeof FloorDatabaseDottxtRoute
  '/load': typeof LoadRoute
  '/login': typeof LoginRoute
  '/parts': typeof PartsRoute
  '/problems': typeof ProblemsRoute
  '/sales': typeof SalesRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/trace': typeof TraceRoute
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/blank/$sheet': typeof BlankSheetRoute
  '/dump/$sheet': typeof DumpSheetRoute
  '/sales/$soNumber': typeof SalesSoNumberRoute
  '/tickets/$ticketNumber': typeof TicketsTicketNumberRoute
  '/tickets/new': typeof TicketsNewRoute
  '/work-orders/$woNumber': typeof WorkOrdersWoNumberRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/export.zip': typeof ExportDotzipRoute
  '/floor-database.txt': typeof FloorDatabaseDottxtRoute
  '/load': typeof LoadRoute
  '/login': typeof LoginRoute
  '/parts': typeof PartsRoute
  '/problems': typeof ProblemsRoute
  '/sales': typeof SalesRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/trace': typeof TraceRoute
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/blank/$sheet': typeof BlankSheetRoute
  '/dump/$sheet': typeof DumpSheetRoute
  '/sales/$soNumber': typeof SalesSoNumberRoute
  '/tickets/$ticketNumber': typeof TicketsTicketNumberRoute
  '/tickets/new': typeof TicketsNewRoute
  '/work-orders/$woNumber': typeof WorkOrdersWoNumberRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/export.zip': typeof ExportDotzipRoute
  '/floor-database.txt': typeof FloorDatabaseDottxtRoute
  '/load': typeof LoadRoute
  '/login': typeof LoginRoute
  '/parts': typeof PartsRoute
  '/problems': typeof ProblemsRoute
  '/sales': typeof SalesRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/trace': typeof TraceRoute
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/blank/$sheet': typeof BlankSheetRoute
  '/dump/$sheet': typeof DumpSheetRoute
  '/sales/$soNumber': typeof SalesSoNumberRoute
  '/tickets/$ticketNumber': typeof TicketsTicketNumberRoute
  '/tickets/new': typeof TicketsNewRoute
  '/work-orders/$woNumber': typeof WorkOrdersWoNumberRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dispatch'
    | '/export.zip'
    | '/floor-database.txt'
    | '/load'
    | '/login'
    | '/parts'
    | '/problems'
    | '/sales'
    | '/shipping'
    | '/tasks'
    | '/tickets'
    | '/trace'
    | '/work-orders'
    | '/blank/$sheet'
    | '/dump/$sheet'
    | '/sales/$soNumber'
    | '/tickets/$ticketNumber'
    | '/tickets/new'
    | '/work-orders/$woNumber'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dispatch'
    | '/export.zip'
    | '/floor-database.txt'
    | '/load'
    | '/login'
    | '/parts'
    | '/problems'
    | '/sales'
    | '/shipping'
    | '/tasks'
    | '/tickets'
    | '/trace'
    | '/work-orders'
    | '/blank/$sheet'
    | '/dump/$sheet'
    | '/sales/$soNumber'
    | '/tickets/$ticketNumber'
    | '/tickets/new'
    | '/work-orders/$woNumber'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dispatch'
    | '/export.zip'
    | '/floor-database.txt'
    | '/load'
    | '/login'
    | '/parts'
    | '/problems'
    | '/sales'
    | '/shipping'
    | '/tasks'
    | '/tickets'
    | '/trace'
    | '/work-orders'
    | '/blank/$sheet'
    | '/dump/$sheet'
    | '/sales/$soNumber'
    | '/tickets/$ticketNumber'
    | '/tickets/new'
    | '/work-orders/$woNumber'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DispatchRoute: typeof DispatchRoute
  ExportDotzipRoute: typeof ExportDotzipRoute
  FloorDatabaseDottxtRoute: typeof FloorDatabaseDottxtRoute
  LoadRoute: typeof LoadRoute
  LoginRoute: typeof LoginRoute
  PartsRoute: typeof PartsRoute
  ProblemsRoute: typeof ProblemsRoute
  SalesRoute: typeof SalesRouteWithChildren
  ShippingRoute: typeof ShippingRoute
  TasksRoute: typeof TasksRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  TraceRoute: typeof TraceRoute
  WorkOrdersRoute: typeof WorkOrdersRouteWithChildren
  BlankSheetRoute: typeof BlankSheetRoute
  DumpSheetRoute: typeof DumpSheetRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export.zip': {
      id: '/export.zip'
      path: '/export.zip'
      fullPath: '/export.zip'
      preLoaderRoute: typeof ExportDotzipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-database.txt': {
      id: '/floor-database.txt'
      path: '/floor-database.txt'
      fullPath: '/floor-database.txt'
      preLoaderRoute: typeof FloorDatabaseDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/load': {
      id: '/load'
      path: '/load'
      fullPath: '/load'
      preLoaderRoute: typeof LoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank/$sheet': {
      id: '/blank/$sheet'
      path: '/blank/$sheet'
      fullPath: '/blank/$sheet'
      preLoaderRoute: typeof BlankSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dump/$sheet': {
      id: '/dump/$sheet'
      path: '/dump/$sheet'
      fullPath: '/dump/$sheet'
      preLoaderRoute: typeof DumpSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$soNumber': {
      id: '/sales/$soNumber'
      path: '/$soNumber'
      fullPath: '/sales/$soNumber'
      preLoaderRoute: typeof SalesSoNumberRouteImport
      parentRoute: typeof SalesRoute
    }
    '/tickets/$ticketNumber': {
      id: '/tickets/$ticketNumber'
      path: '/$ticketNumber'
      fullPath: '/tickets/$ticketNumber'
      preLoaderRoute: typeof TicketsTicketNumberRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/new': {
      id: '/tickets/new'
      path: '/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof TicketsNewRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/work-orders/$woNumber': {
      id: '/work-orders/$woNumber'
      path: '/$woNumber'
      fullPath: '/work-orders/$woNumber'
      preLoaderRoute: typeof WorkOrdersWoNumberRouteImport
      parentRoute: typeof WorkOrdersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SalesRouteChildren {
  SalesSoNumberRoute: typeof SalesSoNumberRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesSoNumberRoute: SalesSoNumberRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

interface TicketsRouteChildren {
  TicketsTicketNumberRoute: typeof TicketsTicketNumberRoute
  TicketsNewRoute: typeof TicketsNewRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsTicketNumberRoute: TicketsTicketNumberRoute,
  TicketsNewRoute: TicketsNewRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

interface WorkOrdersRouteChildren {
  WorkOrdersWoNumberRoute: typeof WorkOrdersWoNumberRoute
}

const WorkOrdersRouteChildren: WorkOrdersRouteChildren = {
  WorkOrdersWoNumberRoute: WorkOrdersWoNumberRoute,
}

const WorkOrdersRouteWithChildren = WorkOrdersRoute._addFileChildren(
  WorkOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DispatchRoute: DispatchRoute,
  ExportDotzipRoute: ExportDotzipRoute,
  FloorDatabaseDottxtRoute: FloorDatabaseDottxtRoute,
  LoadRoute: LoadRoute,
  LoginRoute: LoginRoute,
  PartsRoute: PartsRoute,
  ProblemsRoute: ProblemsRoute,
  SalesRoute: SalesRouteWithChildren,
  ShippingRoute: ShippingRoute,
  TasksRoute: TasksRoute,
  TicketsRoute: TicketsRouteWithChildren,
  TraceRoute: TraceRoute,
  WorkOrdersRoute: WorkOrdersRouteWithChildren,
  BlankSheetRoute: BlankSheetRoute,
  DumpSheetRoute: DumpSheetRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
